# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, MissingH, parsec, QuickCheck, xml }:

cabal.mkDerivation (self: {
  pname = "TreeFeatures";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ MissingH parsec xml ];
  testDepends = [ MissingH parsec QuickCheck xml ];
  meta = {
    homepage = "http://chriswarbo.net/essays/repos/tree-features.html";
    description = "Feature extraction for tree structured data";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
